services:
  api:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URL=redis:6379
      - PORT=8080=value
    depends_on:
      - redis
      - mongo
    restart: always
  redis:
    container_name: redis
    build: ./redis
    ports:
      - "6379:6379"
    restart: always

  mongo:
    container_name: mongo
    build: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
volumes:
  mongo-data:
